//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SalaryDetail
    {
        public int SCode { get; set; }
        public Nullable<int> EmpNo { get; set; }
        public Nullable<int> DayAttend { get; set; }
        [Required]
        public Nullable<System.DateTime> Period { get; set; }
        public Nullable<int> SalaryAmount { get; set; }
    }
}
